# Generated by Django 5.1.4 on 2024-12-23 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="заголовок")),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="описание"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
                ("execute_at", models.DateTimeField(verbose_name="выполнить в")),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="клиент",
                    ),
                ),
            ],
        ),
    ]
