# Generated by Django 5.1.4 on 2024-12-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name="имя пользователя",
                    ),
                ),
                (
                    "telegram_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="id телеграм"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC+05:00", verbose_name="часовой пояс(utc)"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="пароль"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="активный"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="менеджер"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="администратор"),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата регистрации"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
                "ordering": ("-id",),
            },
        ),
    ]
