# Generated by Django 5.1.4 on 2024-12-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="telegram_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="id телеграм"
            ),
        ),
    ]
