# Generated by Django 5.1.4 on 2024-12-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ("-telegram_id",),
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.RemoveField(
            model_name="client",
            name="id",
        ),
        migrations.AlterField(
            model_name="client",
            name="telegram_id",
            field=models.PositiveBigIntegerField(
                default=0,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id телеграм",
            ),
        ),
    ]
